import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import { ApiError, apiClient, type AdminAccountDetail, type RoleCode } from '../../lib/api/client'
import { useAuth } from '../auth/AuthProvider'

const roles: Array<{ code: RoleCode; label: string }> = [{ code: 'individual', label: '个人' }, { code: 'enterprise', label: '企业' }, { code: 'government', label: '政府' }, { code: 'admin', label: '管理员' }]

export function AdminAccountEditorPage() {
  const { userId } = useParams(); const editing = Boolean(userId); const navigate = useNavigate(); const { state, getAccessToken } = useAuth()
  const [role, setRole] = useState<RoleCode>('individual'); const [form, setForm] = useState<Record<string, string>>({}); const [departments, setDepartments] = useState<Array<{ department_id: string; department_name: string }>>([]); const [loaded, setLoaded] = useState<AdminAccountDetail | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => { void apiClient.getRegistrationDepartments().then(setDepartments).catch(() => setDepartments([])) }, [])
  useEffect(() => { if (!editing || state.status !== 'ready' || !state.identity.roles.includes('admin')) return; const token = getAccessToken(); if (!token || !userId) return; void apiClient.getAdminAccount(userId, token).then((item) => { setLoaded(item); setRole(item.roles[0] ?? 'individual'); setForm({ display_name: item.display_name, email: item.email ?? '', contact_phone: item.contact_phone ?? '', job_title: item.job_title ?? '', organization_id: item.organization_id ?? '', department_id: item.department_id ?? '' }) }).catch((cause) => setError(cause instanceof ApiError ? cause.message : '账号详情暂不可用。')) }, [editing, getAccessToken, state, userId])
  if (state.status !== 'ready' || !state.identity.roles.includes('admin')) return <section className="page-content empty-state"><h1>无权访问</h1></section>
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); const token = getAccessToken(); if (!token) return; setBusy(true); setError(null); try { if (editing && userId) await apiClient.updateAdminAccount(userId, { display_name: form.display_name, email: form.email || null, contact_phone: form.contact_phone || null, job_title: form.job_title || null, role_code: role, organization_id: form.organization_id || null, department_id: form.department_id || null }, token); else await apiClient.createAdminAccount(role, { username: form.username, password: form.password, password_confirmation: form.password_confirmation, display_name: form.display_name, email: form.email || null, contact_phone: form.contact_phone || null, job_title: form.job_title || null, ...(role === 'enterprise' ? { enterprise_name: form.enterprise_name, organization_code: form.organization_code, organization_id: null } : {}), ...(role === 'government' ? { department_id: form.department_id } : {}) }, token); navigate('/account-management') } catch (cause) { setError(cause instanceof ApiError ? cause.message : '账号保存失败。') } finally { setBusy(false) } }
  return <section className="page-content account-editor-page"><Link className="policy-back-link" to="/account-management">返回账号管理</Link><div className="eyebrow">Account editor</div><h1>{editing ? '编辑账号' : '新增账号'}</h1>{editing && !loaded ? <p className="muted">正在读取账号…</p> : <form className="admin-policy-form" onSubmit={submit}><div className="policy-fields"><label><span>账号类型</span><select value={role} onChange={(e) => setRole(e.target.value as RoleCode)}>{roles.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>{!editing ? <><label><span>登录账号</span><input required value={form.username ?? ''} onChange={(e) => set('username', e.target.value)} /></label><label><span>密码</span><input required minLength={12} type="password" value={form.password ?? ''} onChange={(e) => set('password', e.target.value)} /></label><label><span>确认密码</span><input required minLength={12} type="password" value={form.password_confirmation ?? ''} onChange={(e) => set('password_confirmation', e.target.value)} /></label></> : null}<label><span>显示名称</span><input required value={form.display_name ?? ''} onChange={(e) => set('display_name', e.target.value)} /></label><label><span>邮箱</span><input type="email" value={form.email ?? ''} onChange={(e) => set('email', e.target.value)} /></label><label><span>联系电话</span><input value={form.contact_phone ?? ''} onChange={(e) => set('contact_phone', e.target.value)} /></label><label><span>职务</span><input value={form.job_title ?? ''} onChange={(e) => set('job_title', e.target.value)} /></label>{role === 'enterprise' && !editing ? <><label><span>企业名称</span><input required value={form.enterprise_name ?? ''} onChange={(e) => set('enterprise_name', e.target.value)} /></label><label><span>企业组织代码</span><input required value={form.organization_code ?? ''} onChange={(e) => set('organization_code', e.target.value)} /></label></> : null}{role === 'enterprise' && editing ? <label><span>企业组织 ID</span><input required value={form.organization_id ?? ''} onChange={(e) => set('organization_id', e.target.value)} /></label> : null}{role === 'government' ? <label><span>政府部门</span><select required value={form.department_id ?? ''} onChange={(e) => set('department_id', e.target.value)}><option value="">请选择部门</option>{editing && loaded?.department_id ? <option value={loaded.department_id}>{loaded.department_name}</option> : null}{departments.map((item) => <option key={item.department_id} value={item.department_id}>{item.department_name}</option>)}</select></label> : null}</div>{error ? <p className="error-message">{error}</p> : null}<div className="admin-policy-actions"><button className="button button-primary" disabled={busy}>{busy ? '正在保存…' : '保存账号'}</button></div></form>}</section>
}
