import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ApiError, apiClient, type AdminApplicationDetail } from '../../lib/api/client'
import { useAuth } from '../auth/AuthProvider'

export function AdminRegistrationApplicationDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { state, getAccessToken } = useAuth(); const [item, setItem] = useState<AdminApplicationDetail | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [decision, setDecision] = useState<'approve' | 'reject' | null>(null); const [decisionText, setDecisionText] = useState('')
  useEffect(() => { if (state.status !== 'ready') return; const token = getAccessToken(); if (!token || !id || !state.identity.roles.includes('admin')) return; void apiClient.getAdminRegistrationApplication(id, token).then(setItem).catch((cause) => setError(cause instanceof ApiError ? cause.message : '申请详情暂不可用。')) }, [getAccessToken, id, state])
  if (state.status !== 'ready' || !state.identity.roles.includes('admin')) return <section className="page-content empty-state"><h1>无权访问</h1></section>
  if (!item) return <section className="page-content empty-state"><h1>{error ? '申请不可用' : '正在读取申请'}</h1><p>{error}</p></section>
  const token = getAccessToken() ?? ''
  async function submitDecision() { if (!item || !decision || (decision === 'reject' && !decisionText.trim())) return; setBusy(true); try { const next = decision === 'approve' ? await apiClient.approveRegistrationApplication(item.id, decisionText, token) : await apiClient.rejectRegistrationApplication(item.id, decisionText, token); setItem(next); navigate('/registration-applications', { replace: true }) } catch (cause) { setError(cause instanceof ApiError ? cause.message : '审批操作失败。') } finally { setBusy(false) } }
  return <section className="page-content admin-application-detail"><Link to="/registration-applications">← 返回申请列表</Link><div className="eyebrow">{item.application_type === 'enterprise' ? 'Enterprise' : 'Government'} application</div><h1>{item.title}</h1><p>使用人：{item.user_name} · 登录账号：{item.login_username}</p><dl className="application-fields">{Object.entries(item.form_data).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value ?? '未设置')}</dd></div>)}</dl>{error ? <p className="error-message" role="alert">{error}</p> : null}{item.status === 'pending' ? <div className="role-mismatch-actions"><button className="button button-primary" disabled={busy} onClick={() => { setDecision('approve'); setDecisionText('') }}>通过申请</button><button className="button button-secondary" disabled={busy} onClick={() => { setDecision('reject'); setDecisionText('') }}>拒绝申请</button></div> : <p className="inline-notice">该申请已处理：{item.status}</p>}{decision ? <div className="approval-dialog-backdrop"><div className="approval-dialog" role="dialog" aria-modal="true" aria-labelledby="approval-dialog-title"><h2 id="approval-dialog-title">{decision === 'approve' ? '确认通过申请' : '确认拒绝申请'}</h2><label><span>{decision === 'approve' ? '审批备注（可选）' : '拒绝原因'}</span><textarea autoFocus required={decision === 'reject'} value={decisionText} onChange={(event) => setDecisionText(event.target.value)} /></label><div className="role-mismatch-actions"><button className="button button-primary" disabled={busy || (decision === 'reject' && !decisionText.trim())} onClick={() => void submitDecision()}>{busy ? '正在处理…' : '确认提交'}</button><button className="button button-secondary" disabled={busy} onClick={() => setDecision(null)}>取消</button></div></div></div> : null}</section>
}
